### ISSUE TITLE
Feature request: support feed ECG data to Tileio via local file and HTTP streaming, rather than WebBLE/WebUSB

### ISSUE THREAD

**Issue by mhfan** [AmbiqAI/tileio#10]
So the great Tileio can demo in a quicker local way that is independent of hardware, and can be used in some kind of remote ECG sensing application scenario.

**Comment by apage224** [comment]
Thanks for your interest. Tileio is primarily aimed at streaming and displaying real-time data from Ambiq devices (not just ECG) for demo purposes. Streaming via HTTP might be an option in future. I don't see a use case for local file.
